steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/launchpulse-ai/luxury-fragrance-brand:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/launchpulse-ai/luxury-fragrance-brand:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/launchpulse-ai/luxury-fragrance-brand:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/launchpulse-ai/luxury-fragrance-brand:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'luxury-fragrance-brand'
      - '--image'
      - 'gcr.io/launchpulse-ai/luxury-fragrance-brand:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/launchpulse-ai/luxury-fragrance-brand:$COMMIT_SHA'
  - 'gcr.io/launchpulse-ai/luxury-fragrance-brand:latest'

options:
  logging: CLOUD_LOGGING_ONLY
